on: [push]
name: secret
jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
    - name: Install databricks-cli
      run: pip install --upgrade databricks-cli
    - uses: actions/checkout@v1
    - name: Dump secret to file
      shell: bash
      env:
        DATABRICKS_SECRET: ${{ secrets.SuperSecret }}
      run: echo "$DATABRICKS_SECRET" > secret.txt
    - name: List files
      run: ls
