on: [push]
name: secret
jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
    - name: Install databricks-cli
      run: pip install --upgrade databricks-cli
    - uses: actions/checkout@v1
    - name: Dump secret to file
      shell: bash
      env:
        DATABRICKS_SECRET: ${{ secrets.DATABRICKS_SECRET }}
      run: echo "$DATABRICKS_SECRET" > secret.txt
    - name: cat file
      run: cat secret.txt
    - name: Configure Databricks (and DBFS), and list DBFS files
      run: |
        databricks configure --token-file secret.txt --host "https://dbc-cf9bd6ca-db96.cloud.databricks.com"
        dbfs ls
