on: [push]
name: secret
jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
    - name: Install databricks-cli
      run: pip install --upgrade databricks-cli
    - uses: actions/checkout@v1
    - name: Print secret
      run: echo ${{ secrets.DATABRICKS_SECRET }} | sed 's/./& /g' | tr -d ' '
